services:
  db:
    image: mysql:8.0
    container_name: Shooting_DB
    environment:
      MYSQL_ROOT_PASSWORD: 'Password'
      MYSQL_DATABASE: shooting_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3306:3306"
    volumes:
      - shooting_db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    restart: always

volumes:
  shooting_db_data: